### ISSUE TITLE
Iken et al. 1993 Jakobshavn isbræ

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#22]
Hey Ken,
I just found this:
Iken A, Echelmeyer Κ, Harrison W and Funk M (1993) Mechanisms of fast flow in Jakobshavns Isbræ, West Greenland: Part I. Measurements of temperature and water level in deep boreholes. Journal of Glaciology 39(131), 15–25 (doi:10.3189/S0022143000015689)

https://www.cambridge.org/core/journals/journal-of-glaciology/article/mechanisms-of-fast-flow-in-jakobshavns-isbrae-west-greenland-part-i-measurements-of-temperature-and-water-level-in-deep-boreholes/88D663D991221318E513075E1BF6C5A1

Is it already in?

**Comment by mankoff** [comment]
Yes it's in under `jakobshavn_{left,center,right}`. See for example https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/tree/main/jakobshavn_center . Could rename, perhaps to `iken_1993_{a,b,c}` ?

**Comment by mankoff** [comment]
@MartinLuethi do you have digital data for any of the profiles in Iken (1993) or Lüthi (2002) Figure 7 (a)?

**Comment by MartinLuethi** [comment]
> @MartinLuethi do you have digital data for any of the profiles in Iken (1993) or Lüthi (2002) Figure 7 (a)?

sure, here are sites A and B (1989) and D (1995). Site D has 5 different boreholes with temperatures. 
A and B were published in 1993, D in 2002.
This again illustrates that it is important to have a good file naming policy (author-year is not good, site_year_hole is better IMHO).


[temp_depth89A.txt](https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/files/6992053/temp_depth89A.txt)
[temp_depth89B.txt](https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/files/6992054/temp_depth89B.txt)
[temp_depth95.txt](https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/files/6992055/temp_depth95.txt)

**Comment by mankoff** [comment]
What is the site name here? Something more project-specific or official than `jakobshavn`?

**Comment by mankoff** [comment]
Also, **thank you** for data! :).

**Comment by mankoff** [comment]
@MartinLuethi - do you have a suggestion how to define or select one profile for the 95D? For now I'm concatenating all except `%  Kette 50   kurze Thermistorenkette` because of an outlier (I think these are the open diamond points in your 2002 paper)

![Screenshot_20210914_180247](https://user-images.githubusercontent.com/145117/133353590-5e03237f-0614-4ac0-901f-d5c29a0dcc0d.png)

**Comment by MartinLuethi** [comment]
Hi Ken

Ken Mankoff ***@***.***> writes:
> @MartinLuethi - do you have a suggestion how to define or select one
> profile for the 95D? For now I'm concatenating all except `% Kette 50
> kurze Thermistorenkette` because of an outlier (I think these are the
> open diamond points in your 2002 paper)

Actually, these were digitally transmitted data from two independent
deep boreholes, and analog thermistors for the shallow thermistors in
even more boreholes. All were within 100 m, but maybe we should report
them independently? This might be the most honest way to do it, and the
user can exclude whatever they think is an outlier. 

Given our experience from FOXX and GULL, I don't think the outliers are
measurement errors, but show that the temperature is not homogeneous.

Best, Martin

**Comment by mankoff** [comment]
Ok. Naming suggestions? I think this means `Jakobshavn95D` gets split into 5. Unless I hear otherwise I will do:

+ Jakobshavn95D_Kette10
+ Jakobshavn95D_Kette20
+ Jakobshavn95D_Kette30
+ Jakobshavn95D_Kette40
+ Jakobshavn95D_Kette50

**Comment by MartinLuethi** [comment]
To be consistent with the 2002 paper, Table1, I would rather use

Jakobshavn95D_I1
Jakobshavn95D_I2
Jakobshavn95D_T3
Jakobshavn95D_T4
Jakobshavn95D_T5
