### ISSUE TITLE
Laika Ice Cap & John Evans Glacier

### ISSUE THREAD

**Issue by mjacqu** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#39]
Hi GEUS team!

Cool stuff you are doing here! I am actually working on a complementary effort for mountain glaciers (or more specifically any thing that is within the RGI), I've done most of the world but for Greenland, so wanted to know whether you would be ok with me pulling what data you have for RGI glaciers in Greenland and the surrounding islands. Since you've also included data from some of the peripheral islands in your dataset, I also wanted to share the data that I've found for Laika Ice Cap (Coburn Island) and John Evans Glacier (Ellesmere Island). Is that something you'd be interested in?

I look forward to hearing from you! You can also reach me directly at jacquemart@vaw.baug.ethz.ch

Cheers,
Mylène

**Comment by mankoff** [comment]
Hello! Thank you for reaching out.

This database is open/public. You are welcome to pull and use for your own purposes, but please cite.

You are welcome to email me (kdm ... geus.dk) your Laika and JE data, or attach it to this ticket, or issue a pull request with everything (metadata, reformatted data, etc.) - whichever you prefer.
