### ISSUE TITLE
More complete information for HansTausen_Dome

### ISSUE THREAD

**Issue by ezwelty** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#50]
Your information for [`HansTausen_Dome`](https://github.com/GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles/blob/8b28d0e7333426426ac377615663ba735e5623f9/boreholes/HansTausen_Dome/README.org) is incomplete. According to the original reference, temperature was measured at more than two points. Here the info @mjacqu and I extracted, as part of our [`glenglat`](https://github.com/mjacqu/glenglat) project.

### source: `hammer1995`

id | author | year | type | title | url | language | container_title | volume | issue | page | version | editor | collection_title | collection_number | publisher
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
hammer1995 | Claus Uffe Hammer | 1995 | chapter | Ice core drilling |   | en | Report on activities and results 1993-1995 for Hans Tausen Ice Cap Project - Glacier and Climate Change Research, North Greenland |   |   | 16-28 |   | Niels Reeh | NMRs (Nordisk Minister Råd) miljøforskningsprogram - klimaforskning |   | Dansk Polar Center

source files: [glenglat/sources/hammer1995](https://github.com/mjacqu/glenglat/tree/main/sources/hammer1995), namely [Figure 6](https://github.com/mjacqu/glenglat/blob/main/sources/hammer1995/figure-6.png).

### borehole: `232`

id | source_id | glacier_name | glims_id | location_origin | latitude | longitude | elevation_origin | elevation | label | date_min | date_max | drill_method | ice_depth | depth | to_bed | temperature_accuracy | notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
232 | hammer1995 | Hans Tausen Ice Cap | G323085E82488N | published | 82.492 | -37.477 | published | 1271 | HT95 | 1995-05-29 | 1995-06-20 | mechanical |   | 344.86 | True |   | location_origin: reeh1995 (Figure 3) \| elevation_origin: steffensen2001

### profile: `232` – `1`

borehole_id | id | source_id | measurement_origin | date_min | date_max
-- | -- | -- | -- | -- | --
232 | 1 | hammer1995 | digitized | 1995-06-20 | 1995-12-31

### measurements

borehole_id | profile_id | depth | temperature
-- | -- | -- | --
232 | 1 | 11.687 | -19.438
232 | 1 | 20.163 | -20.845
232 | 1 | 30.235 | -20.779
232 | 1 | 40.316 | -20.704
232 | 1 | 60.547 | -20.491
232 | 1 | 81.209 | -20.265
232 | 1 | 100.547 | -20.107
232 | 1 | 119.968 | -19.872
232 | 1 | 139.407 | -19.621
232 | 1 | 159.693 | -19.357
232 | 1 | 179.618 | -19.043
232 | 1 | 199.565 | -18.707
232 | 1 | 219.535 | -18.350
232 | 1 | 239.455 | -18.040
232 | 1 | 259.439 | -17.671
232 | 1 | 279.876 | -17.268
232 | 1 | 299.796 | -16.957
232 | 1 | 321.048 | -16.571
232 | 1 | 340.528 | -16.282

**Comment by mankoff** [comment]
Do you have a copy of the `Hammer 1995` paper? From your https://github.com/mjacqu/glenglat/blob/5ab102004d6cece032bc5a22dc75f8b3b78cd664/data/source.csv#L58 I see

```
hammer1995	
Claus Uffe Hammer	
1995	
chapter	
Ice core drilling		
en	
Report on activities and results 1993-1995 for Hans Tausen Ice Cap Project - Glacier and Climate Change Research, North Greenland			
16-28		
Niels Reeh	
NMRs (Nordisk Minister Råd) miljøforskningsprogram - klimaforskning		
Dansk Polar Center
```

But I am unable to find a copy.

**Comment by ezwelty** [comment]
@mankoff Sent to the email in your profile.
