### ISSUE TITLE
Neil Humphrey's name is misspelled

### ISSUE THREAD

**Issue by ezwelty** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#52]
Sorry for another little nitpick issue! But I was deduplicating author names in glenglat, and came across "Neil Humphrey" and "Niel Humphrey". The latter is incorrect and comes from your dataset's metadata. Since there's a repo for that, I figured I would report it.

**Comment by mankoff** [comment]
Thank you! I'm a fan of nitpicking, no need to apologize.
