### ISSUE TITLE
1930/31 German expedition cores

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#8]
+ See citet:heuberger_1956  https://link.springer.com/article/10.1007/BF02122819
  + References other documents by page #, but no reference to those docs
  + Note - found Wegener (1955), but not 1930/31 expedition (unless that expedition data was published in `55).

**Comment by BaptisteVandecrux** [comment]
Jakob Abermann has digitized the report from that expedition. I have the temperature in the top 15 m. Don't know if they measured further down. You can drop Jakob an email for more info.

**Comment by mankoff** [comment]
From J. Abermann:

> They came down to ca. 15 m below the surface, not deeper. 
If you need a reference for this, you can use this - temperatures are given in Tab 1
https://www.cambridge.org/core/journals/journal-of-glaciology/article/sorges-law-of-densification-of-snow-on-high-polar-glaciers/11F52DA59A607AC2C9ACDC24BEB63156
I also looked at their reports and there they write a sort of 'digging diary' and end up excusing themselves for not having gotten any deeper...
